spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://54.180.140.193:5432/stocking 
      username: stocking
      password: stocking1234 
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  config: classpath:logback-spring.xml

logging.level.yahoofinance.histquotes2.HistQuotes2Request: ERROR
  
---
spring:
  profiles: local
  
---
spring:
  profiles: production
  jpa:
    show-sql: false
