spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  config: classpath:logback-spring.xml

logging.level.yahoofinance.histquotes2.HistQuotes2Request: ERROR
  
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://arjuna.db.elephantsql.com:5432/kfnzwjso
      username: kfnzwjso
      password: PN6khtXWIbRT_aeYwnMqSKFx81C8637B
      driver-class-name: org.postgresql.Driver
  
---
spring:
  profiles: production
  jpa:
    show-sql: false
  datasource:
    hikari:
      jdbc-url: ${STOCKING_JDBC_URL}
      username: ${STOCKING_USER}
      password: ${STOCKING_PASSWORD}
      driver-class-name: org.postgresql.Driver
