spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://arjuna.db.elephantsql.com:5432/kfnzwjso 
      username: kfnzwjso
      password: M75X9usBzmjW4xdelDwzolmzT73lnYb1 
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---
spring:
  profiles: dev
  
